### ISSUE TITLE
I get a java.lang.reflect.TargetInvocationException

### ISSUE THREAD

**Issue by mrg12** [bricolsoftconsulting/SetAlwaysFinish#2]
I downloaded the source and put a printStackTrace in the writeFinishOptions method catch clause and then i see the cause:

?:??: W/?(?): Caused by: java.lang.SecurityException: Permission Denial: setAlwaysFinish() from pid=8475, uid=10008 requires android.permission.SET_ALWAYS_FINISH

However that permission is already in your Manifest. What is going wrong here?

/mrg12

p.s. I have a Google Nexus with Android 4.1

**Comment by bricolsoftconsulting** [comment]
I don't currently have access to a Galaxy Nexus and Jellybean, so can't take a look right now to see what has changed. I do have a Nexus S available, so as soon as JellyBean is available for Nexus S I will give this a try.

My guess is that the SET_ALWAYS_FINISH permission has been restricted so it's only available to system apps. Take a look at this question: http://stackoverflow.com/questions/9063549/how-to-grant-system-permission

Here is what I recommend:
1. If you just need to do manual testing, then ICS (and probably JellyBean too) now include a similar option. In ICS it's under Settings > Developer Options > Apps (section) > Don't keep activities.
2. If you need to perform automated testing, then uninstall the current SetAlwaysFinish app and try to place the SetAlwaysFinish APK in the system/apps folder. To do that you will need to run root and remount the system partition as rw. Alternatively, you can try to create an update package that you can flash into the ROM with ClockWorkMod ROM Manager.

I'd be interested to know if using system/app or root helps. If you do decide to try it, let me know what you find.

**Comment by mrg12** [comment]
Thank you for you quick and useful reply!

In all fairness i should do automated testing but i will go for recommendation #1. Seems like Android partly implemented the fucntionality of your testing tool in their newest versions of Android.

**Comment by mrg12** [comment]
I did notice during debug sessions that indeed the activity has been destroyed and gets recreated while using your proposed method #1 (and i assume it is the same with the apk solution), but that global values stored in getApplication() are sometimes still available. The problem i ran into in real life situations occurred bacuse i assumed that the activity can always get required global objects from Application, but that is not always the case. This particular part doesn't seem to be testable this way.

Do you have any ideas?

**Comment by bricolsoftconsulting** [comment]
Well, I believe that if you terminate all the activities and there are no remaining activities in the app stack then that probably indicates to the Android OS that the app is no longer running, so it will probably remove the entire app from memory, including your Application globals. Just a guess though, not really sure.

**Comment by bricolsoftconsulting** [comment]
You can probably test using DDMS (or ps if you have a rooted device). Look at the list of processes and see whether the entire app process gets destroyed when you exit the last Activity.

**Comment by mrg12** [comment]
In DDMS i still see my package as process when i have the 4.1 developer option (don't_keep_alive) on and i move my only activity in the background. So i think the application stays alive for a while (even if there are no activities anymore) and will get destroyed at a later moment when Android feels its time has come.

Btw i will close the issue as your first comment got me what i needed to know. Once you have 4.1 yourself you might be able to find a way to get it running again for automated testing on 4.1.
